Numpy is fundamental library for scientific computing in python . it provides support for arrays and matrices along with collection of mathematical function to operate on data structure


In [6]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

##create arrays using numpy
#create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [19]:
#reshape
#2D array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 column
arr2.reshape(5,1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [3]:
arr2 =np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
arr2.shape
arr2.reshape(5,2)

[[1 2 3 4 5]
 [2 3 4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]])

In [4]:
##arrays witn in-buit function
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [22]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
##identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
##attributes of numpy
arr = np.array([[1,2,3] , [4,5,6]])

print("Array:\n",arr)
print("shape :",arr.shape)
print("numbers of dimension :",arr.ndim)
print("Size (number of element) :",arr.size)
print("Data type:",arr.dtype)
print("Item size (in byte):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
shape : (2, 3)
numbers of dimension : 2
Size (number of element) : 6
Data type: int64
Item size (in byte): 8


In [25]:
##Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

##element wise addition
print("Addition:",arr1+arr2)

###element wise substraction
print("substraction:", arr1 - arr2)


###element wise multiplication
print("multiplication:", arr1 * arr2)


###element wise substraction
print("division:", arr1 / arr2)

Addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [6]:
##universal function

arr = np.array([2,3,4,5,6])
##square root
print("square root:",np.sqrt(arr))

##exponential
print("exponential:",np.exp(arr))

##natural log
print("Natural log:",np.log(arr))

square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Natural log: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [3]:
## array slicing and indexing
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
print(arr[0][0])

1


In [4]:
arr[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [51]:
arr[0:2,2:]


array([[3, 4],
       [7, 8]])

In [53]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [54]:
##modify array elemets
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [56]:
arr[1:] = 100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [59]:
##statastical concept
#Normalization
#to have a mean of 0 standard deviation of 1
data = np.array([1,2,3,4,5])
data.size
data.shape

##calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#normalize the data
normalize_data = (data - mean) / std_dev
print("normalize data :",normalize_data )



normalize data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [15]:
##calculate mean,median,standard deviation,variance
data = np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean = np.mean(data)
print("mean :", mean)

#median 
median = np.median(data)
print("median :", median)

#standard deviation
std_dev = np.std(data)
print("standard deviation:", std_dev )

#variance
variance =  np.var(data)
print("variance:" ,variance)


mean : 5.5
median : 5.5
standard deviation: 2.8722813232690143
variance: 8.25


In [7]:
## logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data >=5) & (data <= 8)]
# print(data.reshape(10,1))

array([5, 6, 7, 8])